/home/pl217/miniconda3/envs/simpler_env/lib/python3.11/site-packages/huggingface_hub/file_download.py:896: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/pl217/continualearning/model.py:636: UserWarning: Weight loading missing non-Hopfield keys: ['out_head.weight']
  if missing: warnings.warn(f"Weight loading missing non-Hopfield keys: {missing}")
/home/pl217/continualearning/model.py:266: UserWarning: Error assigning sampled embeddings (shape mismatch?): shape '[24, 256, 128]' is invalid for input of size 18874368. Falling back to random.
  warnings.warn(f"Error assigning sampled embeddings (shape mismatch?): {e}. Falling back to random.")
/home/pl217/continualearning/data_loader.py:56: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self._processed_data = torch.load(self.cache_path)
Epoch 1:   0%|          | 0/2047 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/pl217/continualearning/train.py", line 525, in <module>
    train(config_file)
  File "/home/pl217/continualearning/train.py", line 340, in train
    for step, batch in enumerate(train_dataloader):
  File "/home/pl217/miniconda3/envs/simpler_env/lib/python3.11/site-packages/accelerate/data_loader.py", line 566, in __iter__
    current_batch = next(dataloader_iter)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pl217/miniconda3/envs/simpler_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/pl217/miniconda3/envs/simpler_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pl217/miniconda3/envs/simpler_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/home/pl217/miniconda3/envs/simpler_env/lib/python3.11/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/pl217/miniconda3/envs/simpler_env/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/pl217/miniconda3/envs/simpler_env/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pl217/continualearning/data_loader.py", line 258, in collate_fn
    padded_inputs = tokenizer.pad(
                    ^^^^^^^^^^^^^^
TypeError: PreTrainedTokenizerBase.pad() got an unexpected keyword argument 'truncation'

Epoch 1:   0%|          | 0/2047 [00:04<?, ?it/s]
